name: MySQL CI

on:
  push:
    branches: [ main ]

jobs:
  mysql-job:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for MySQL
        run: sleep 20

      - name: Install MySQL client
        run: sudo apt-get install -y mysql-client

      - name: Run SQL script and verify
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -proot < create_tables.sql
          mysql -h 127.0.0.1 -P 3306 -u root -proot -e "USE demo; SELECT * FROM students;"
